### ISSUE TITLE
获取token失败，请尝试更换网络环境

### ISSUE THREAD

**Issue by qazwsdc** [qiushaungzheng/kuaishou-live-barrage#1]
另外不论怎么换房间id，返回的第一行都是liveStreamId uMvasYlp-vY这个

**Comment by qazwsdc** [comment]
应该是无法获取到房间信息了
这个库还有效吗

**Comment by qazwsdc** [comment]
换了ip解决了，但获取到的liveStreamId似乎并不是指定房间的
而且这个免登录对ip要求极高，很快就不能用了，频繁换ip

**Comment by zzzzqs** [comment]
目前都是基于kuaishou web端来实现的，快手好像对web端不太重视，目前也没有什么比较好的办法
