### ISSUE TITLE
这直播间id是什么啊试了好几种都不行艾

### ISSUE THREAD

**Issue by icerain2023** [qiushaungzheng/kuaishou-live-barrage#3]
![image](https://github.com/qiushaungzheng/kuaishou-live-barrage/assets/121789653/593bd06e-6084-47dc-8cbd-222a2ae2f325)

**Comment by zzzzqs** [comment]
我更新了获取liveStreamId的方式 但是获取ws链接的时候会触发快手的风控 暂时无解，有兴趣可以看下源码

**Comment by icerain2023** [comment]
![image](https://github.com/qiushaungzheng/kuaishou-live-barrage/assets/121789653/8ff64c0e-ed6c-4285-876a-ab43f60f62d2)
这直播id是u/后面的这个吗

**Comment by zzzzqs** [comment]
是的
